#!/bin/bash
# Check if the command is 'install'
if [ "$#" -ne 1 ]; then
    echo "Usage: ./run install"
    exit 1
fi
command=$1

if [ "$command" = "install" ]; then
    pip3 install -r requirements.txt
    exit $?
elif [ "$command" = "build" ]; then
    # tsc.cmd src/urlhandler.ts
    tsc.cmd
    # node src/urlhandler.js
    node src/main_program.js
    exit $?
elif [ "$command" = "test" ]; then
    echo "Running tests..."
    python3 -m pytest test/
    exit $?
else
    echo "HI"
    # if [[ "$command" =~ ^[a-zA-Z]: ]]; then
    # command=$(cygpath -u "$command")
    # fi
    
    # if [ -f "$command" ]; then
    #     # do file things
    #     if [[ "$command" == *.txt ]]; then
    #         # echo "This is a valid text file filepath."
    #         #tsc.cmd
    #         npx tsc
    #         node src/main_program.js "$command"
    #         find src/frontend/src -type f -name '*.js' -delete
    #         exit $?;
    #     else 
    #         echo "This is not a valid text file filepath."
    #         exit 1;
    #     fi
    # else 
    #     echo "Not a valid argument. Command must be either 'install', 'test', or a valid file path to a text file."
    #     exit 1;
    fi
fi
